name: 번역 오류 제보
description: 번역이나 글자 표현에 오류가 있을 경우
title: "[번역 오류 제보]: "
labels: []
body:
  - type: markdown
    attributes:
      value: |
        스크린샷을 첨부하거나 [텍스트 오류 제보 가이드](https://github.com/ToD-DC-Kor/kor-patch/blob/main/CONTRIBUTING.md#%ED%85%8D%EC%8A%A4%ED%8A%B8-%EC%98%A4%EB%A5%98-%EC%A0%9C%EB%B3%B4)를 따라 제보해주세요.

        텍스트 오류 제보 가이드를 따르지 못했다면, 도움이 되는 스크린샷을 첨부해주세요. 번역 오류는 스크린샷이 크게 도움 됩니다.
  - type: textarea
    id: detail
    attributes:
      label: 번역 오류에 대한 설명
      description: 번역 오류에 대해 설명해주세요.
      placeholder: 무슨 일이 일어나고 있나요?
    validations:
      required: true
  - type: textarea
    id: explain
    attributes:
      label: (선택사항) 재현 방법
      description: 번역 오류가 단순하지 않을 경우, 재현해서 고칠 수 있도록 재현 할 수 있는 세이브 파일과 재현 방법을 적어주세요.
      placeholder: |
        세이브 파일을 로드한 시점부터 문제가 발생하는 곳까지 도달하는 재현 방법을 적어주세요. 모든 던전과 맵의 지도를 외우고 있지 못하기 때문에, 자세히 설명해 주셔야 합니다.
        예시)
        
        1. 첨부한 세이브 파일 로드
        2. 오른쪽 문으로 나가서, 건물 바로 앞의 NPC 말걸기
        3. 등등...
  - type: input
    id: version
    attributes:
      label: 패치 버전
    validations:
      required: true
  - type: textarea
    id: extra
    attributes:
      label: 추가 정보
      description: 추가로 전달하고 싶은 정보가 있다면 적어주세요.
